package com.wellu.usermanagement.mapper;

import com.wellu.usermanagement.dto.request.MedicationCreateRequestDto;
import com.wellu.usermanagement.dto.response.MedicationResponseDto;
import com.wellu.usermanagement.dto.request.MedicationUpdateRequestDto;
import com.wellu.usermanagement.entity.HealthProfile;
import com.wellu.usermanagement.entity.Medication;
import org.mapstruct.*;

@Mapper(componentModel = "spring")
public interface MedicationMapper {

    // Create request -> entity
    @Mapping(target = "id", ignore = true) // generated by DB
    @Mapping(target = "healthProfile", source = "healthProfile")
    @Mapping(target = "endDate", source = "request.endDate")
    Medication toEntity(MedicationCreateRequestDto request, HealthProfile healthProfile);

    // Entity -> response
    @Mapping(target = "healthProfileId", source = "healthProfile.id")
    MedicationResponseDto toResponse(Medication medication);

    // Update entity (partial update)
    @BeanMapping(nullValuePropertyMappingStrategy = NullValuePropertyMappingStrategy.IGNORE)
    @Mapping(target = "id", ignore = true)
    @Mapping(target = "healthProfile", ignore = true)
    Medication updateEntityFromDto(MedicationUpdateRequestDto request, @MappingTarget Medication medication);

}
