ALTER TABLE profiles
    ADD COLUMN IF NOT EXISTS gender VARCHAR(50),
    ADD COLUMN IF NOT EXISTS fitness_level VARCHAR(100),
    ADD COLUMN IF NOT EXISTS main_goal VARCHAR(100);

ALTER TABLE medications
    ALTER COLUMN dosage DROP NOT NULL,
    ALTER COLUMN frequency DROP NOT NULL,
    ALTER COLUMN start_date DROP NOT NULL,
    ADD COLUMN IF NOT EXISTS reason VARCHAR(255);
